[tool.poetry]
name = "python-discord-bot"
version = "0.1.0"
description = ""
authors = ["Kevin <kevin.roy@owasp.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyppeteer-stealth = "^2.7.4"
playwright = "^1.42.0"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.3"
curl-cffi = "^0.6.2"
newspaper3k = "^0.2.8"
termcolor = "^2.4.0"
uvicorn = "^0.29.0"
fastapi = "^0.110.0"
paramiko = "^3.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
